### ISSUE TITLE
Пропадает кнопка лайка при долгом нажатии

### ISSUE THREAD

**Issue by polevskyy** [Followy-Dev/Android-BugTracker#1]
**Опишите возникший баг**
Четкое и краткое описание ошибки.

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Перейти к "..."
2. Щелкните "...."
3. Прокрутите вниз до "...."
4. Наблюдайте ошибку

**Ожидаемое поведение**
Четкое и краткое описание того, что вы ожидали.

**Скриншоты**
Если возможно, добавьте скриншоты, чтобы объяснить вашу проблему.

**Система (заполните следующую информацию):**
 - ОС: [к прим. Android(чистый)/MIUI]
 - Версия ОС [к прим. 7.0]
 - Модель телефона [к прим. Meizu m6s/Honor 9A]

**Дополнительная информация**
Добавьте сюда любую другую информацию о проблеме.

**Comment by BrightOS** [comment]
Не смог воспроизвести данный баг. Распишите его, пожалуйста, чуть-чуть подробнее.
