### ISSUE TITLE
Заморозка интерфейса при нажатии на кнопки

### ISSUE THREAD

**Issue by whosqeade** [Followy-Dev/Android-BugTracker#10]
Двойное нажатие или просто быстрые нажатия на вкладки "профиль" и "лента" блокируют загрузку данных и деактивируют остальные кнопки

**Для воспроизведения**
1. Дважды или более нажать на иконку "лента" или "профиль" навбаре
2. Наблюдайте ошибку: новости в ленте входят в бесконечную загрузку. Вкладка профиль входит в бесконечную загрузку. Все кнопки, кроме навбара становятся неактивными.

**Ожидаемое поведение**
Корректная работа приложения

**Система:**
 - ОС: MIUI 12.0.4
 - Android 10
 - Xiaomi Redmi Note 8

**Comment by BrightOS** [comment]
Исправлено. Будет доступно в следующем обновлении
