### ISSUE TITLE
краш при тройном нажатии

### ISSUE THREAD

**Issue by gxl0grxma** [Followy-Dev/Android-BugTracker#12]
**Опишите возникший баг**
краш при тройном нажатии на кнопку опубликовать запись

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. зайти в профиль
2. нажать на поле, которое открывает создание записи
3. написать что либо, чтобы пост опубликовался
4. три раза нажать на кнопку опубликовать пост

**Ожидаемое поведение**
закрытие формы создания записи

**Скриншоты**
![Screenshot_2021-05-05-23-04-25-654_ru followy](https://user-images.githubusercontent.com/76883683/117188620-b0850600-adf6-11eb-80ec-8021d44f7e2f.jpg)

**Система (заполните следующую информацию):**
 - ОС: miui
 - 12.0.6.0
 - rn9

**Дополнительная информация**

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
