### ISSUE TITLE
Системные сообщения

### ISSUE THREAD

**Issue by lopatincmd** [Followy-Dev/Android-BugTracker#13]
**Шаги по воспроизведению поведения:**
1. Перейти к настройкам
2. Поменяйте имя пользователя
3. Всплывет системный текст ю

**Система:**
 - ОС: Android 10, MIUI 12.0.2
 - Модель телефона: Redmi Note 7
![IMG_20210506_031021](https://user-images.githubusercontent.com/83724057/117189424-2601ce00-ae19-11eb-9c99-040a9dd33ec0.jpg)

**Comment by BrightOS** [comment]
Меню настроек будет ещё долгое время дорабатываться. Баг будет исправлен в одной из ближайших версий.

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
