### ISSUE TITLE
Вылет при переходе в настройки

### ISSUE THREAD

**Issue by gxl0grxma** [Followy-Dev/Android-BugTracker#14]
**Опишите возникший баг**
краш при нажатии на настройки

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. опубликовать любой пост
2. зайти в глобал ленту
3. нажать на свою аватарку/профиль
4. открыть настройки

**Ожидаемое поведение**
настройки откроются

**Скриншоты**
![Screenshot_2021-05-05-23-13-56-589_ru followy](https://user-images.githubusercontent.com/76883683/117189603-d363ea00-adf7-11eb-9eee-826dc465a52d.jpg)

**Система (заполните следующую информацию):**
 - ОС: miui
 - 12.0.6.0
 - rn9

**Дополнительная информация**

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии.

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
