### ISSUE TITLE
Рассинхронизация ника после смены такого

### ISSUE THREAD

**Issue by ghost** [Followy-Dev/Android-BugTracker#15]
**Опишите возникший баг**
После смены ника через API ник в приложении меняется только в постах

**Для воспроизведения**
Меняем ник через апи, перезапускаем приложение

**Ожидаемое поведение**
Ник в профиле тоже меняется

**Скриншоты**
![image](https://user-images.githubusercontent.com/43349083/117193635-c93bee80-adeb-11eb-8cb8-071d516a2b91.png)
![image](https://user-images.githubusercontent.com/43349083/117193652-cd680c00-adeb-11eb-9fc9-a352187ee379.png)

На стороне апи:
![image](https://user-images.githubusercontent.com/43349083/117194211-7ca4e300-adec-11eb-9776-f987d747fb49.png)

**Система (заполните следующую информацию):**
 - ОС: PixelExpirience
 - Версия ОС: 10
 - Модель телефона: Amber

**Дополнительная информация**
нет

**Comment by BrightOS** [comment]
Синхронизация имени основного пользователя идёт при запуске приложения. Предложение о добавлении дополнительной синхронизации принято и будет рассмотрено в ближайшее время.

**Comment by ghost** [comment]
Странно, но после перезапуска ник все равно не изменяется, о чем я написал в репорте, так что прошу перепроверить код

**Comment by BrightOS** [comment]
Будет исправлено в следующем обновлении. Закрыто.
