### ISSUE TITLE
Вечная загрузка при многократном нажатии

### ISSUE THREAD

**Issue by cry-crystal** [Followy-Dev/Android-BugTracker#16]
При многократном нажатии на иконку Профиля или Ленты оба этих раздела перестают загружаться. 

Шаги по воспроизведению поведения:
1. Перейти в любой из доступных 
2. Щелкните по иконке Ленты или профиля около 15-20 раз
3. Наблюдайте ошибку. Оба раздела не грузятся в течение часа

Ожидалось срабатывание на первый клик и игнорирование последующих. 

Видео: https://disk.yandex.ru/i/kfR0DiaE9pnq_A

**Система:**
 - ОС: MIUI
 - Версия ОС: 12.0.3
 - Модель телефона: Xiaomi Redmi Note 9 Pro

**Дополнительная информация**
При меньшем количестве нажатий начинает грузиться дольше, но прогружает.

**Comment by mazzz3r** [comment]
дубль #6
