### ISSUE TITLE
Дублирование записей и краш

### ISSUE THREAD

**Issue by cry-crystal** [Followy-Dev/Android-BugTracker#17]
**Опишите возникший баг**
При многократном нажатии на кнопку Опубликовать запись публикуется сразу несколько одинаковых записей, а после происходит краш

Шаги по воспроизведению поведения:
1. Перейти в интерфейс создания записи и напишите что-то
2. Щелкните по кнопке Создать запись много раз
3. Наблюдайте ошибку. Создание нескольких записей и краш приложения. 

Ожидалось срабатывание на первый клик и игнорирование последующих. 

Видео: https://disk.yandex.ru/i/ypL5GTi3dVPgBA

**Система (заполните следующую информацию):**
 - ОС: MIUI
 - Версия ОС: 12.0.3
 - Модель телефона: Xiaomi Redmi Note 9 Pro

**Дополнительная информация**
-

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии.
