### ISSUE TITLE
Бесконечная загрузка приложения

### ISSUE THREAD

**Issue by whosqeade** [Followy-Dev/Android-BugTracker#18]
Бесконечная загрузка приложения со включенным интернетом

**Для воспроизведения**
1. Зайти в приложение с выключенным интернетом (мобильным, доступа к wi-fi пока нет)
2. На загрузочном экране с градиентом включить интернет.
3. Наблюдать проблему: загрузка данныхсю с сервера не производится, хоть интернет и включен

**Ожидаемое поведение**
Корректный вход и работоспособность  приложения

 - ОС: MIUI 12.0.4
 - Android 10
 - Xiaomi Redmi Note 8

**Comment by BrightOS** [comment]
Будет исправлено в следующем обновлении. Закрыто.
