### ISSUE TITLE
краш при отсутствии интернета

### ISSUE THREAD

**Issue by gxl0grxma** [Followy-Dev/Android-BugTracker#19]
**Опишите возникший баг**
краш при отсутствии интернета

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. зайти в приложение с включенным интернетом
2. выключить интернет когда появится ваш профиль
3. нажать на значок глобал ленты

**Ожидаемое поведение**
заглушка о том, что у юзера нет интернета

**Скриншоты**
![Screenshot_2021-05-06-11-51-10-642_ru followy](https://user-images.githubusercontent.com/76883683/117254335-b7952e00-ae61-11eb-9857-8b05b242a75b.png)

**Система (заполните следующую информацию):**
 - ОС: miui
 - 12.0.6.0
 - rn9

**Дополнительная информация**

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
