### ISSUE TITLE
Невозможно модернизировать выделенный текст

### ISSUE THREAD

**Issue by haun01** [Followy-Dev/Android-BugTracker#2]
**Опишите возникший баг**
Когда выделяю текст появляется клавиатура, закрывающая кнопки для смены стиля текста.

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Перейти к профилю
2. Перейди в диалог с созданием поста
3. Написать текст и попытаться выделить его
4. Данный текст нельзя стилизировать

**Ожидаемое поведение**
После выделения текста клавиатура не должна появляется, чтобы можно было стилизировать текст

**Видеозапись**
https://dropmefiles.com/9JmHt

**Система (заполните следующую информацию):**
 - ОС: Android(EMUI 5.1.3)
 - Версия ОС 7.0
 - Модель телефона: Honor 6A

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
