### ISSUE TITLE
Получение ошибки, невозможность авторизации в аккаунте

### ISSUE THREAD

**Issue by ghost** [Followy-Dev/Android-BugTracker#20]
**Опишите возникший баг**
Вызов ошибки, невозможность зайти в аккаунт

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. Регистрируем аккаунт, на этапе подтверждения мыла сначала кликаем кнопку подтвердить, на что приложение нам пишет что мы все еще не подтвердили аккаунт
2. подтверждаем мыло
3. опять кликаем подтвредить и в приложении и ловим ошибку.

**Ожидаемое поведение**
Авторизация в аккаунте

**Скриншоты**
1. сама ошибка
![image](https://user-images.githubusercontent.com/43349083/117275403-af8bbd00-ae66-11eb-9534-fba9359564da.png)
2. после этого закидывает на этот экран
![image](https://user-images.githubusercontent.com/43349083/117275482-c29e8d00-ae66-11eb-9d17-8bef20c012f6.png)
3. невозможно после таких событий зайти в аккаунт (бесконечная загрузка, проверял при интернете мобильном и от роутера)
![image](https://user-images.githubusercontent.com/43349083/117275600-dd710180-ae66-11eb-879f-9848e933a276.png)
4. на стороне сервера авторизация работает
![image](https://user-images.githubusercontent.com/43349083/117275766-0beedc80-ae67-11eb-862b-7b2d42e7a0fe.png)
5. при попытке вызвать метод апи, получаем ответ о недостатке привелегий
![image](https://user-images.githubusercontent.com/43349083/117275882-2aed6e80-ae67-11eb-8e5f-bebee9e839e4.png)

**Система (заполните следующую информацию):**
 - ОС: Linage OS (no gapps)
 - Версия ОС: 10
 - Модель телефона: Yandex Amber

**Дополнительная информация**
Конкретно описать что пошло по пизде не могу

**Comment by ghost** [comment]
После переустановки приложения, авторизация все также не работает, подозрение на баг в апи

**Comment by ghost** [comment]
Проверил апи, создал аккаунт таким же способом. При попытке авторизации в приложении снова бесконечная загрузка. Если ввести невалидные данные, то приложение сообщит об их невалидности, из чего делаю вывод что это дело не связано с плохой скоростью интернет соединения

**Comment by ghost** [comment]
Пробовал с другого аккаунта
![image](https://user-images.githubusercontent.com/43349083/117280572-68ec9180-ae6b-11eb-8509-7462a2a94bbb.png)
![image](https://user-images.githubusercontent.com/43349083/117280585-6be78200-ae6b-11eb-8229-2bb80f657011.png)
![image](https://user-images.githubusercontent.com/43349083/117280598-6f7b0900-ae6b-11eb-8961-e94bbe3f5afb.png)
![image](https://user-images.githubusercontent.com/43349083/117280624-74d85380-ae6b-11eb-875f-3fecc871c126.png)
Авторизация все так же не работает

**Comment by ghost** [comment]
При создании аккаунта человеческим способом
![image](https://user-images.githubusercontent.com/43349083/117282779-caadfb00-ae6d-11eb-85f9-e631f88d8ce4.png)

**Comment by G1fl3x** [comment]
Еще раз перепроверил апи, ошибка полностью на стороне клиента

**Comment by mazzz3r** [comment]
Ошибка известна, суть в том, что в приложении нет обработки роли `0`, которая теперь выдаётся новым юзерам. Считай, что фикс
