### ISSUE TITLE
логотип

### ISSUE THREAD

**Issue by gxl0grxma** [Followy-Dev/Android-BugTracker#21]
**Ваш запрос функции связан с проблемой? Пожалуйста, опишите.**
пиксели на рту у логотипа
![IMG_20210509_101001](https://user-images.githubusercontent.com/76883683/117561290-0257b580-b0af-11eb-95ba-963df5759ad1.jpg)

**Опишите решение, которое вы хотите**
рот без пикселей, как и глаза

**Опишите альтернативы, которые вы рассмотрели**
логотип без пикселей на рту

**Дополнительная информация**
а почему рот в пикселях

**Comment by mazzz3r** [comment]
Нам прислать логотип, нарисованный гуашью или как? Куда нам пиксели то деть
