### ISSUE TITLE
Некорректное поведение "курсора" клавиатуры при изменении настроек текста

### ISSUE THREAD

**Issue by whosqeade** [Followy-Dev/Android-BugTracker#26]
"курсор" переносится в начало напечатанного текста при использовании кнопок форматирования текста без выделения этого самого текста

Шаги по воспроизведению поведения:
1. Во вкладке "новая запись" напечатать любой текст.
2. Перенести курсор клавиатуры в любую часть текста
3. Не выделяя текст нажать любую из трёх кнопок форматирования текста
4. Лицезреть перемещение курсора в начало строки 

**Ожидаемое поведение**
Изменение форматирования конкретного слова в котором стоит курсор, или попросту отсутствие поведения

 - ОС: MIUI 12.0.5
 - android 10
 - Xiaomi Redmi note 8

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии приложения
