### ISSUE TITLE
Множество диалоговых окон

### ISSUE THREAD

**Issue by haun01** [Followy-Dev/Android-BugTracker#3]
# Опишите возникший баг

При множественном нажатии кнопки "создать пост" вылазит множество диалоговых окон

# Шаги по воспроизведению поведения:

1. Перейти к профилю
2. много раз нажать на кнопку "создать пост"
3. Наблюдать недочёт

# Ожидаемое поведение
Появится одно диалоговое окно

# Видеозапись
https://dropmefiles.com/UesRd

# Система:

ОС: Android(EMUI 5.1.3)
Версия ОС 7.0
Модель телефона: Honor 6A****

**Comment by BrightOS** [comment]
Принято к рассмотрению. В ближайшее время займусь данной проблемой.

**Comment by BrightOS** [comment]
Будет исправлено в следующей версии. Закрыто.
