### ISSUE TITLE
я захватил ленту. 

### ISSUE THREAD

**Issue by haun01** [Followy-Dev/Android-BugTracker#4]
# Опишите возникший баг
Нет лимита на добавление постов в ленту от одного пользователя. (Возможно заспамить рекламой)

# Шаги по воспроизведению поведения:

1. написать очень много постов
2. зайти в ленту 

# Ожидаемое поведение
В ленте появится максимум 2 новых поста от меня

# Видеозапись
https://dropmefiles.com/4sibJ

# Система:

ОС: Android(EMUI 5.1.3)
Версия ОС 7.0
Модель телефона: Honor 6A

**Дополнительная информация**
Добавьте сюда любую другую информацию о проблеме.

**Comment by BrightOS** [comment]
Расчисткой глобальной ленты в будущем будут заниматься модераторы. Эту проблему, скорее всего, хорошо было бы осветить конкретно в баг-трекере API, чтобы были добавлены некоторые ограничения на публикацию постов. Закрыто.
