### ISSUE TITLE
исчезновение постов в глобал ленте

### ISSUE THREAD

**Issue by gxl0grxma** [Followy-Dev/Android-BugTracker#6]
**Опишите возникший баг**
пропадает содержимое глобал ленты после многочисленных нажатий на значок глобал ленты

**Для воспроизведения**
Шаги по воспроизведению поведения:
1. нажать на значок глобал ленты
2. _**очень очень много**_ раз нажать на этот самый значок

**Ожидаемое поведение**
содержимое глобал ленты будет видно

**Скриншоты**
![Screenshot_2021-05-05-22-01-49-413_ru followy](https://user-images.githubusercontent.com/76883683/117180682-df4aae80-aded-11eb-9e01-0263f171998a.jpg)

**Система (заполните следующую информацию):**
 - ОС: miui
 - 12.0.6.0
 - rn9

**Дополнительная информация**

**Comment by haun01** [comment]
Вообще-то, лента после каждого нажатия обновляется и это всё зависит от скорости интернета

**Comment by BrightOS** [comment]
Будет исправлено в следующем обновлении. Закрыто.
