### ISSUE TITLE
Некорректная анимация

### ISSUE THREAD

**Issue by whosqeade** [Followy-Dev/Android-BugTracker#8]
Анимация умудряется зависнуть при длительном нажатии на кнопку "новая запись"  или “настройки“

Шаги по воспроизведению поведения:
1. Перейти к вкладке Профиль
2. Щелкнуть и удержать одну из выше преуказанных кнопок
3. Не отрывая палец от экрана переместите его в другое место
4. Наблюдайте ошибку

**Ожидаемое поведение**
Нормальное исполнение и окончание анимации

![Screenshot_2021-05-05-20-13-41-849_ru.followy.jpg](https://user-images.githubusercontent.com/82702231/117181955-714abb00-adde-11eb-858f-15750f3e7c2d.jpg)
![Screenshot_2021-05-05-20-13-44-413_ru.followy.jpg](https://user-images.githubusercontent.com/82702231/117182193-ba027400-adde-11eb-9477-a9f5a4a78b23.jpg)
![Screenshot_2021-05-05-20-13-46-506_ru.followy.jpg](https://user-images.githubusercontent.com/82702231/117182213-bf5fbe80-adde-11eb-91b3-26bfc2fa8a8f.jpg)
![Screenshot_2021-05-05-20-13-50-853_ru.followy.jpg](https://user-images.githubusercontent.com/82702231/117182227-c25aaf00-adde-11eb-86f9-6036615a49e5.jpg)

**Система:**
 - ОС: MIUI 12.0.4 global
 - Android 10
 - Xiaomi Redmi Note 8 

**Дополнительная информация**
Либо я тупой и не понял как прикреплять запись экрана, либо обидно что этого тут нет. Надеюсь, по скринам воспроизвести получилось

**Comment by BrightOS** [comment]
Будет исправлено в следующем обновлении. Закрыто.
